[deps]
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeoMakie = "db073c08-6b98-4ee5-b6a4-5efafb3259c6"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GeometryOps = "3251bfac-6a57-4b6d-aa61-ac1fef2975ab"
GibbsSeaWater = "9a22fb26-0b63-4589-b28e-8f9d0b5c3d05"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LibGEOS = "a90b1aa1-3769-5649-ba7e-abc5a9d163eb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MUMPS = "55d2b088-9f4e-11e9-26c0-150b02ea6a46"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
NaturalEarth = "436b0209-26ab-4e65-94a9-6526d86fea76"
NetCDF = "30363a11-5582-574a-97bb-aa9a979735b9"
NonlinearSolve = "8913a72c-1f9b-4ce2-8d82-65094dcecaec"
OceanBasins = "d1bb7020-b2be-4340-9d18-d24ca645bddb"
OceanTransportMatrixBuilder = "c2b4a04e-6049-4fc4-aa6a-5508a29a1e1c"
PETSc = "ace2c81b-2b5f-4b1e-a30d-d662738edfe0"
Pardiso = "46dd5b70-b6fb-5a00-ae2d-e8fea33afaf2"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
YAXArrays = "c21b50f5-aa40-41ea-b809-c0f5e47bfa5c"
